# Generated by Django 4.2.3 on 2025-11-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=500)),
                ('artist_name', models.CharField(max_length=500)),
                ('album_name', models.CharField(blank=True, max_length=500)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('spotify_url', models.URLField()),
                ('album_art_url', models.URLField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommendations_count', models.IntegerField(default=0)),
                ('source', models.CharField(default='spotify', max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-fetch_timestamp'],
            },
        ),
    ]
